[package]
name = "thrussh-test"
version = "0.1.0"
authors = ["MggMuggins <mggmugginsmc@gmail.com>"]

[dependencies]
thrussh = { path = "../thrussh/thrussh" }
thrussh-keys = { path = "../thrussh/thrussh-keys" }
env_logger = "0.5.9"
futures = "0.1.21"
tokio = { path = "../tokio" }
ring = "0.12.1"
